
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSDOUBLE EQUALS HIT ID INT MINUS PLUS SPLIT\n        print : E\n              | empty\n              | action\n        \n        E : R EQUALS S\n        \n        R : ID\n        \n        S : L MINUS F\n        \n        F : F PLUS L\n        \n        F : L\n        \n        L : INT\n        \n        action : DOUBLE\n               | SPLIT\n               | HIT\n        \n        empty :\n        '
    
_lr_action_items = {'$end':([0,1,2,3,4,6,7,8,11,13,15,16,18,],[-13,0,-1,-2,-3,-10,-11,-12,-4,-9,-8,-6,-7,]),'DOUBLE':([0,],[6,]),'SPLIT':([0,],[7,]),'HIT':([0,],[8,]),'ID':([0,],[9,]),'EQUALS':([5,9,],[10,-5,]),'INT':([10,14,17,],[13,13,13,]),'MINUS':([12,13,],[14,-9,]),'PLUS':([13,15,16,18,],[-9,-8,17,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'print':([0,],[1,]),'E':([0,],[2,]),'empty':([0,],[3,]),'action':([0,],[4,]),'R':([0,],[5,]),'S':([10,],[11,]),'L':([10,14,17,],[12,15,18,]),'F':([14,],[16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> print","S'",1,None,None,None),
  ('print -> E','print',1,'p_print','blackjack_parser.py',57),
  ('print -> empty','print',1,'p_print','blackjack_parser.py',58),
  ('print -> action','print',1,'p_print','blackjack_parser.py',59),
  ('E -> R EQUALS S','E',3,'p_E','blackjack_parser.py',67),
  ('R -> ID','R',1,'p_R','blackjack_parser.py',74),
  ('S -> L MINUS F','S',3,'p_S','blackjack_parser.py',81),
  ('F -> F PLUS L','F',3,'p_F','blackjack_parser.py',88),
  ('F -> L','F',1,'p_F_L','blackjack_parser.py',95),
  ('L -> INT','L',1,'p_L','blackjack_parser.py',102),
  ('action -> DOUBLE','action',1,'p_action','blackjack_parser.py',109),
  ('action -> SPLIT','action',1,'p_action','blackjack_parser.py',110),
  ('action -> HIT','action',1,'p_action','blackjack_parser.py',111),
  ('empty -> <empty>','empty',0,'p_empty','blackjack_parser.py',122),
]
